version: 0.2

env:
  secrets-manager:
    ESWITCH_ARTIFACOTRY_USERNAME: "aws/artifactory:username"
    ESWITCH_ARTIFACOTRY_PASSWORD: "aws/artifactory:password"
    GITHUB_ACCESS_TOKEN: "aws/github/e-switch-ch:access.token"
    SNYK_TOKEN: "aws/snyk/e-switch-ch:snyk.token"
    CLOUDWATCH_ACCESS_KEY_ID: "aws/cloudwatch:accessKeyId"
    CLOUDWATCH_SECRET_ACCESS_KEY: "aws/cloudwatch:secretAccessKey"

phases:
  install:
    commands:
      - echo $(date +"%F %T.%N") install phase started
      - yum update -y
      - yum -y install ant
      - # install latest maven
      - # yum install -y maven # resolves to outdated maven 3.0
      - maven_version=3.9.5
      - wget -q https://dlcdn.apache.org/maven/maven-3/${maven_version}/binaries/apache-maven-${maven_version}-bin.tar.gz
      - tar -xf apache-maven-${maven_version}-bin.tar.gz
      - rm apache-maven-${maven_version}-bin.tar.gz
      - mv apache-maven-${maven_version} /usr/local/apache-maven
      - export M2_HOME=/usr/local/apache-maven
      - export M2=$M2_HOME/bin
      - export PATH=$M2:$PATH
      - mvn --version
    finally:
      - echo $(date +"%F %T.%N") install phase ended
  pre_build:
    commands:
      - echo $(date +"%F %T.%N") pre_build phase started
    finally:
      - echo $(date +"%F %T.%N") pre_build phase ended
  build:
    commands:
      - echo $(date +"%F %T.%N") build phase started
      - pwd
      - echo ESWITCH_ARTIFACOTRY_USERNAME $ESWITCH_ARTIFACOTRY_USERNAME
      - PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.4.0:evaluate -Dexpression=project.version -q -DforceStdout)
      - echo PROJECT_VERSION $PROJECT_VERSION
      - mvn --no-transfer-progress -s settings.xml clean deploy
    finally:
      - echo $(date +"%F %T.%N") build phase ended
  post_build:
    commands:
      - echo $(date +"%F %T.%N") post_build phase started
      - cd $CODEBUILD_SRC_DIR
      - ls -a
      - rm .dccache
      - git status
      - git add snyk-result.json
      - git status
      - git config --global user.email "dev@e-switch.ch"
      - git config --global user.name "e-switch Solutions Developer"
      - git commit -a -m "snyk-result.json" -m "AWS CodeBuild, build number $CODEBUILD_BUILD_NUMBER" -m "$CODEBUILD_BUILD_ARN"
      - git status
      - git add README.md
      - git status
      - git commit -a -m "README.md" -m "AWS CodeBuild, build number $CODEBUILD_BUILD_NUMBER" -m "$CODEBUILD_BUILD_ARN"
      - git tag v$PROJECT_VERSION
      - git status
      - echo GITHUB_ACCESS_TOKEN $GITHUB_ACCESS_TOKEN
      - git remote add github_eswitch https://e-switch-ch:$GITHUB_ACCESS_TOKEN@github.com/e-switch-Solutions-AG/tinylog-aws-cloudwatch-logs-writer
      - git remote -v
      - git push github_eswitch HEAD:main --force
      - git push --tags github_eswitch
    finally:
      - echo $(date +"%F %T.%N") post_build phase ended

artifacts:
  files:
    - '*.jar'
  base-directory: target
  name: jar